### ISSUE TITLE
Can Modal send a status update once the transcription is done?

### ISSUE THREAD

**Issue by aakashb09** [mharrvic/fast-audio-video-transcribe-with-whisper-and-modal#3]
Thank you for this repo, especially because I am very new to Modal. Super easy and helpful for me to transcribe audio directly from links.

I send my URL and get a `call_id`. I have written a simple `while True` with `time.sleep(120)` to check if the call_id returns `{"finished":True}` and only then proceed with further data processing of the transcriptions received.

Is there a mechanism to get the status of the `call_id` from Modal? If yes, where and how do we write it?

**Comment by mharrvic** [comment]
Hey @aakashb09, just saw this; apologies for the super late response.

As per the readme instructions, you can get the status of call_id by
`curl --location 'your-modal-endpoint/api/status/your-call-id'`

Currently, I have no idea of getting the status of that call-id directly from Modal programmatically, but you can check the logs from the Modal app dashboard.
