### ISSUE TITLE
bug - module not found

### ISSUE THREAD

**Issue by rayli09** [mharrvic/fast-audio-video-transcribe-with-whisper-and-modal#4]
<img width="949" alt="image" src="https://user-images.githubusercontent.com/99834841/235224216-758ba510-0a57-42bf-a785-4fa239825736.png">

**Comment by aakashb09** [comment]
Same issue. Any fix for this?

**Comment by mharrvic** [comment]
Hi @aakashb09 will dig more into this. The main functionalities work; just skip the status fetching part for now and directly fetch the getting of the transcript by title; it should respond with `transcription not yet available` for WIP transcriptions.

**Comment by mharrvic** [comment]
Hi @aakashb09. i pushed an update. The issue was just an outdated modal-client package 😅 . Closing this now. Thanks!
